version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./config.yaml:/app/config.yaml
    environment:
      CONFIG_PATH: /app/config.yaml
    networks:
      - fastapi_network
    restart: always 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  fastapi_network:
    driver: bridge
