version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app_internal
    ports:
      - "8000:8000"
    volumes:
      - ./internal:/app/internal
      - ./config.yaml:/app/config.yaml
    environment:
      CONFIG_PATH: /app/config.yaml
    networks:
      - hackaton_hacknet
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  hackaton_hacknet:
    driver: bridge
